name = "PlutoDevMacros"
uuid = "a0499f29-c39b-4c5c-807c-88074221b949"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.8.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
MacroTools = "0.5"
Pkg = "1"
TOML = "1"
julia = "1.9"
